#!/usr/bin/env python3
"""Regenerate docs/CATALOG.md from the on-disk skill tree.

Every skill dir with a SKILL.md becomes a row under its category. The header,
category counts, and skill rows are all derived from disk, so they can never
drift again.

Run:  python3 scripts/gen-catalog.py   (writes docs/CATALOG.md)
"""
import os
import re
import sys
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKILLS = os.path.join(ROOT, "skills")
OUT = os.path.join(ROOT, "docs", "CATALOG.md")


def collect():
    cats = {}
    for cat in sorted(os.listdir(SKILLS)):
        cp = os.path.join(SKILLS, cat)
        if not os.path.isdir(cp):
            continue
        items = []
        # category-level skill dirs
        for d in sorted(os.listdir(cp)):
            p = os.path.join(cp, d)
            if os.path.isdir(p) and os.path.isfile(os.path.join(p, "SKILL.md")):
                text = open(os.path.join(p, "SKILL.md"), encoding="utf-8").read()
                m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
                desc = ""
                if m:
                    try:
                        desc = yaml.safe_load(m.group(1)).get("description", "")
                    except Exception:
                        desc = ""
                items.append((d, str(desc).strip()))
        # category-level SKILL.md (skill not in its own subdir)
        if os.path.isfile(os.path.join(cp, "SKILL.md")):
            text = open(os.path.join(cp, "SKILL.md"), encoding="utf-8").read()
            m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
            desc = ""
            if m:
                try:
                    desc = yaml.safe_load(m.group(1)).get("description", "")
                except Exception:
                    desc = ""
            items.append((cat, str(desc).strip()))
        if items:
            cats[cat] = items
    return cats


def main():
    cats = collect()
    # count unique SKILL.md files (not rows): duplicated names count once
    nfiles = 0
    for root, _dirs, fs in os.walk(SKILLS):
        if "SKILL.md" in fs:
            nfiles += 1
    total = nfiles
    ncats = len(cats)
    out = []
    out.append("# Skill Catalog")
    out.append("")
    out.append(f"**{total} skills** across {ncats} categories, version-controlled for backup "
               "and portability.")
    out.append("")
    out.append("> This file is auto-generated by `scripts/gen-catalog.py`. Do not edit by hand.")
    out.append("")
    for cat, items in sorted(cats.items()):
        out.append(f"## {cat} — {len(items)}")
        out.append("")
        out.append("| Skill | What it does |")
        out.append("|---|---|")
        for name, desc in items:
            # collapse newlines/spaces inside a single row
            desc = re.sub(r"\s+", " ", desc)
            out.append(f"| `{name}` | {desc} |")
        out.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(out))
    print(f"Wrote {OUT}: {total} skills across {ncats} categories.")


if __name__ == "__main__":
    main()